# Generated by Django 5.0.2 on 2024-03-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveStream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='audio_id',
            field=models.IntegerField(null=True),
        ),
    ]
